### ISSUE TITLE
Cannot install CMake Editor on last Eclipse C++ (09-2019)

### ISSUE THREAD

**Issue by bstephgit** [15knots/cmakeed#11]
Hi,

I've tried to install CMake Editor through Ecl. Market place but I got error message :
""
Title: Unable to install selected solutions

Msg: The following solutions are not compatible with this version of Eclipse:

List: CMake editor
""
(I have screenshot if needed)

Any idea?

Thks++

PS: My eclipse version: 
Eclipse IDE for C/C++ Developers
Version: 2019-09 R (4.13.0)
Build id: 20190917-1200

**Comment by 15knots** [comment]
If it was the marketplace showing the message, this should be fixed now.

**Comment by bstephgit** [comment]
I confirm this is fixed. Thanks ^^)
