### ISSUE TITLE
Problem with Installation using the Update Server

### ISSUE THREAD

**Issue by apatwork** [15knots/cmakeed#14]
Hi there,

the cmakeed update setver (https://raw.githubusercontent.com/15knots/cmakeed/master/cmakeed-update) does not seem to function for me. It seems as if the update server were empty. The message I get is "There are no items available".

What could I do to make the update server work?

Thanks a lot in advance for your support.

Regards,

Adalbert.

**Comment by 15knots** [comment]
https://raw.githubusercontent.com/15knots/cmakeed/master/cmakeed-update work here and now.
Possibly a short outtage on github.

**Comment by apatwork** [comment]
Strange! For me the behavior seems to be unchanged. I just checked the log file and found this entry:

!ENTRY org.eclipse.equinox.p2.repository 2 0 2021-01-28 10:16:16.759
!MESSAGE Server returned lastModified <= 0 for https://github.com/15knots/cmakeed/tree/master/cmakeed-update/compositeContent.xml

What does that mean?

Regards,

Adalbert.

**Comment by 15knots** [comment]
> Strange! For me the behavior seems to be unchanged. I just checked the log file and found this entry:
> 
> !ENTRY org.eclipse.equinox.p2.repository 2 0 2021-01-28 10:16:16.759
> !MESSAGE Server returned lastModified <= 0 for https://github.com/15knots/cmakeed/tree/master/cmakeed-update/compositeContent.xml
> 
> What does that mean?

Eclipse is querying the server for updates before downloading the file and issues a HTTP HEAD request with a If-Modified-Since header first. You see the message because github does not respond to HEAD requests [1] which does not harm; Eclipse will just download compositeContent.xml at any time.

Martin

[1] https://www.eclipse.org/forums/index.php?t=msg&th=1104861&goto=1831240&#msg_1831240

**Comment by apatwork** [comment]
Thanks a lot for the explanation, Martin! In between I installed Eclipse on my private computer and tried to install the cmakeed plug-in using your update server. It worked like a charm! So the problem must be in my organisation. My current task is to install Eclipse in our Linux server farm; From the machines in the server farm there is no internet access. This is for security reasons. We have a so called repository manager (Artifactory from JFrog) in place  which  allows to access specific data from the internet. The problem must be located in the configuration of that tool.

Thanks a lot for your quick and helpful support!

Adalbert
