### ISSUE TITLE
build error:Missing requirement: org.eclipse.equinox.p2.repository 2.3.100.v20150428-1613 requires 'java.package; javax.crypto 0.0.0' but it could not be found

### ISSUE THREAD

**Issue by AlexLuya** [15knots/cmakeed#15]
Source commit: d48f42ab43b13e2989e66b574d262a47b7721022   2021-04-22
OS: Ubuntu 20.10
JDK:  15.0.2
Maven: 3.6.3

`mvn -f ./parent/pom.xml verify`

gives error:

INFO] Resolving dependencies of MavenProject: com.cthing.cmakeed:com.cthing.cmakeed.core:1.1.6 @ /home/user/cmakeed/com.cthing.cmakeed.core/pom.xml
[ERROR] Cannot resolve target definition:
[ERROR]   Software being installed: org.eclipse.pde.api.tools.ee.feature.feature.group 1.0.1.v20140424-1723
[ERROR]   Missing requirement: org.eclipse.equinox.p2.repository 2.3.100.v20150428-1613 requires 'java.package; javax.crypto 0.0.0' but it could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.equinox.p2.publisher 1.4.0.v20141117-0929 depends on: java.package; org.eclipse.equinox.p2.repository [2.0.0,3.0.0)
[ERROR]   Cannot satisfy dependency: org.eclipse.pde.api.tools 1.0.700.v20150513-0819 depends on: osgi.bundle; org.eclipse.pde.core [3.3.102,4.0.0)
[ERROR]   Cannot satisfy dependency: org.eclipse.pde.api.tools 1.0.701.v20150831-1041 depends on: osgi.bundle; org.eclipse.pde.core [3.3.102,4.0.0)
[ERROR]   Cannot satisfy dependency: org.eclipse.pde.api.tools.ee.cdcfoundation10 1.0.200.v20130327-1631 depends on: osgi.bundle; org.eclipse.pde.api.tools 1.0.300
[ERROR]   Cannot satisfy dependency: org.eclipse.pde.api.tools.ee.feature.feature.group 1.0.1.v20140424-1723 depends on: org.eclipse.equinox.p2.iu; org.eclipse.pde.api.tools.ee.cdcfoundation10 [1.0.200.v20130327-1631,1.0.200.v20130327-1631]
[ERROR]   Cannot satisfy dependency: org.eclipse.pde.build 3.9.100.v20150521-1524 depends on: osgi.bundle; org.eclipse.equinox.p2.publisher 1.1.0
[ERROR]   Cannot satisfy dependency: org.eclipse.pde.core 3.10.100.v20150522-0332 depends on: osgi.bundle; org.eclipse.pde.build [3.2.0,4.1.0)
[ERROR]   Cannot satisfy dependency: org.eclipse.pde.core 3.10.101.v20150722-0954 depends on: osgi.bundle; org.eclipse.pde.build [3.2.0,4.1.0)
[ERROR]   Cannot satisfy dependency: org.eclipse.pde.core 3.10.102.v20160128-0556 depends on: osgi.bundle; org.eclipse.pde.build [3.2.0,4.1.0)
[ERROR] 
[ERROR] Failed to resolve target definition /home/user/cmakeed/com.cthing.cmakeed-target/com.cthing.cmakeed-target.target: See log for details -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

**Comment by 15knots** [comment]
Build fine here with JDK 11

**Comment by AlexLuya** [comment]
> Build fine here with JDK 11

Doesn't work with JDK 16

**Comment by rhaley-starfish** [comment]
I am currently working on MacOS. I installed each version of Liberica jdk from 16 down to 11 and none of them worked?

```
rhaley@Russells-MBP ~/g/cmake4eclipse> java --version
openjdk 11.0.11 2021-04-20 LTS
OpenJDK Runtime Environment (build 11.0.11+9-LTS)
OpenJDK 64-Bit Server VM (build 11.0.11+9-LTS, mixed mode)
rhaley@Russells-MBP ~/g/cmake4eclipse> set JAVA_HOME (/usr/libexec/java_home)
rhaley@Russells-MBP ~/g/cmake4eclipse> mvn -f ./parent/pom.xml package
[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: de.marw.cdt.cmake:de.marw.cmake.cdt:1.2.1-SNAPSHOT @ /Users/rhaley/git/cmake4eclipse/de.marw.cmake.cdt/pom.xml
[INFO] Fetching p2.index from https://download.eclipse.org/eclipse/updates/4.5/R-4.5.2-201602121500/ (142B)
[INFO] Adding repository https://download.eclipse.org/eclipse/updates/4.5/R-4.5.2-201602121500
[INFO] Fetching p2.index from https://archive.eclipse.org/tools/cdt/releases/8.7/r/ (115B)
[INFO] Adding repository https://archive.eclipse.org/tools/cdt/releases/8.7/r
[INFO] Adding repository http://download.eclipse.org/tools/orbit/downloads/drops/R20130118183705/repository
[INFO] Resolving dependencies of MavenProject: de.marw.cdt.cmake:de.marw.cmake.cdt:1.2.1-SNAPSHOT @ /Users/rhaley/git/cmake4eclipse/de.marw.cmake.cdt/pom.xml
[ERROR] Cannot resolve target definition:
[ERROR]   Software being installed: org.eclipse.pde.api.tools.ee.feature.feature.group 1.0.1.v20140424-1723
[ERROR]   Missing requirement: org.eclipse.equinox.p2.repository 2.3.100.v20150428-1613 requires 'java.package; javax.crypto 0.0.0' but it could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.equinox.p2.publisher 1.4.0.v20141117-0929 depends on: java.package; org.eclipse.equinox.p2.repository [2.0.0,3.0.0)
[ERROR]   Cannot satisfy dependency: org.eclipse.pde.api.tools 1.0.701.v20150831-1041 depends on: osgi.bundle; org.eclipse.pde.core [3.3.102,4.0.0)
[ERROR]   Cannot satisfy dependency: org.eclipse.pde.api.tools.ee.cdcfoundation10 1.0.200.v20130327-1631 depends on: osgi.bundle; org.eclipse.pde.api.tools 1.0.300
[ERROR]   Cannot satisfy dependency: org.eclipse.pde.api.tools.ee.feature.feature.group 1.0.1.v20140424-1723 depends on: org.eclipse.equinox.p2.iu; org.eclipse.pde.api.tools.ee.cdcfoundation10 [1.0.200.v20130327-1631,1.0.200.v20130327-1631]
[ERROR]   Cannot satisfy dependency: org.eclipse.pde.build 3.9.100.v20150521-1524 depends on: osgi.bundle; org.eclipse.equinox.p2.publisher 1.1.0
[ERROR]   Cannot satisfy dependency: org.eclipse.pde.core 3.10.102.v20160128-0556 depends on: osgi.bundle; org.eclipse.pde.build [3.2.0,4.1.0)
[ERROR] 
[ERROR] Failed to resolve target definition /Users/rhaley/git/cmake4eclipse/releng/de.marw.cdt.cmake-target/de.marw.cdt.cmake-target.target: See log for details -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```
