### ISSUE TITLE
Update site not available

### ISSUE THREAD

**Issue by rmspacefish** [15knots/cmakeed#16]
Not sure if I am the only one so..

The update site: https://raw.githubusercontent.com/15knots/cmakeed/master/cmakeed-update/

Is not available for me (error 404). I also can not install the Cmake Editor plugin via Marketplace, probably because of this issue.

Workaround for me: Use this link https://sourceforge.net/projects/cmakeed/files/ in `Install New Software`

**Comment by 15knots** [comment]
The update site on github points to jfrog.io.
Unfortunately, a single IP address downloads the plugin once every minute, thus exhausting the allowed monthly download traffic.
You will have to just wait until next month.

Don't use the surgeforge site, it offers only very old versions of the plugin.

**Comment by AlexLuya** [comment]
same problem here,and self compilation also failed: https://github.com/15knots/cmakeed/issues/15

**Comment by AlexLuya** [comment]
update site is still 'could not find .....'

**Comment by lidochca** [comment]
Could this be related to my issue?
No repository found at jar:https://my-artifactory.com/dl.bintray.com/15knots/p2-zip/CMakeEd-1.17.0.zip!/.
I have successfully installed CMakeEd-1.16.0.zip this way in the past.
So, what should be the correct update site for v. 1.17.0 and what structure does it has, the zip or an unzipped p2 repo?

**Comment by 15knots** [comment]
@lidochca Yes, it is related.

For now, you may download from https://fifteenknots.jfrog.io/artifactory/p2-zip/. 
Pls note that that site has limited download trafiic and some people might exhaust the traffic among since they do a download every minute.

**Comment by 15knots** [comment]
The issue affect cmake4eclips, too and is tracked here: https://github.com/15knots/cmake4eclipse/issues/149

**Comment by kolipakakondal** [comment]
> @lidochca Yes, it is related.
> 
> For now, you may download from https://fifteenknots.jfrog.io/artifactory/p2-zip/.
> Pls note that that site has limited download trafiic and some people might exhaust the traffic among since they do a download every minute.

Having this monthly quota data transfer issue, even if we want to download.
{
  "errors" : [ {
    "status" : 429,
    "message" : "You have reached your monthly quota for Data Transfer. To continue and start enjoying unlimited transfer, upgrade your subscription"
  } ]
}

**Comment by 15knots** [comment]
serving from cloudsmith.io now
