### ISSUE TITLE
Update site returns "400: Invalid request"

### ISSUE THREAD

**Issue by woefulwabbit** [15knots/cmakeed#18]
https://raw.githubusercontent.com/15knots/cmakeed/master/cmakeed-update/

responds with:

400: Invalid request

**Comment by 15knots** [comment]
Yes, since github HTTP server is not configured to return a directory *listing* when you request an URL denoting a directory.
That URL will be properly handle if you enter it as a location in the 'Available Software Site' preference page of your eclipse workbench.
