### ISSUE TITLE
integrate with the clean project command?

### ISSUE THREAD

**Issue by cvgaviao** [15knots/cmakeed#2]
Would be greate to integrate with the clean project command and remove the build directory contents. 
I passed a huge time investigating a build error of a third-party project. 
In the end it was because wrong values of variables cached in the CMakeCache.txt file that was not deleted when I click on "Project/Clean". I fixed them in the cmake editor but it was not being used.

**Comment by 15knots** [comment]
This issue was moved to 15knots/cmake4eclipse#60
