### ISSUE TITLE
update site

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [15knots/cmakeed#9]
seems broken
https://raw.githubusercontent.com/15knots/cmakeed/master/cmakeed-update/
```
400: Invalid request
```

**Comment by 15knots** [comment]
https://raw.githubusercontent.com/15knots/cmakeed/master/cmakeed-update/p2.index
work from here.
Possibly a short glitch on github

**Comment by Andrei-Pozolotin** [comment]
works, thank you
